/**
 * Few-shot exemplars for the customer acknowledgement/action parser
 * (`parseCustomerAckActionWithLLM` in llmDraft.ts).
 *
 * Lifted out of llmDraft.ts verbatim so the prompt corpus can grow without pushing that file
 * past its `source_size_ratchet` ceiling — the ceiling comes DOWN by the number of lines moved.
 * These are STATIC strings: no interpolation, no dependency on the turn being parsed, which is
 * exactly why they can live on their own.
 *
 * Each entry pairs a customer turn WITH the dealer message it answers, because a bare
 * affirmative carries no meaning of its own. The contrast pairs are load-bearing, not
 * decoration: they are what stops a new case cannibalising its neighbours.
 */
export const CUSTOMER_ACK_ACTION_EXEMPLARS: string[] = [
  'input: "Customer: Sounds perfect" history: "out: I have Sat, May 9, 2:00 PM does that work?" output: {"action":"confirm_proposed_appointment","explicit_action":true,"should_reply":true,"should_book":true,"requested":{"day":"sat may 9","time_text":"2:00 PM","time_window":"exact"},"reference":"last_outbound","normalized_text":"sat may 9 2:00 PM","confidence":0.96}',
  'input: "Customer: alright, sounds good man. thank you." history: "out: Hey Rafael, sorry, that would work ill schedule you in between 11-12 tomorrow" output: {"action":"confirm_proposed_appointment","explicit_action":true,"should_reply":false,"should_book":true,"requested":{"day":"tomorrow","time_text":"11-12","time_window":"range"},"reference":"last_outbound","normalized_text":"tomorrow 11-12","confidence":0.94}',
  'input: "Customer: Ok." history: "out: Tuesday between 9:30 and 10:00 can work." output: {"action":"accept_tentative_appointment","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"tuesday","time_text":"9:30-10:00","time_window":"range"},"reference":"last_outbound","normalized_text":"tuesday 9:30-10:00","confidence":0.92}',
  // ACCEPTING OUR OWN OPEN ASK — the `accepted_no_time` funnel bucket (18 leads, 30d to 8/4).
  // Every one of these was previously read as a sign-off and answered with silence or a
  // stand-down line. The contrast pairs below (same words, non-scheduling outbound) are what
  // keep this from over-firing; they are load-bearing, not decoration.
  'input: "Customer: Sounds great!" history: "out: I can get you set up with a time to come see it — what day and time works best for you?" output: {"action":"accept_scheduling_ask","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer accepts coming in, no day or time named","confidence":0.94}',
  'input: "Customer: Sounds good" history: "out: Just text me what day works and I\'ll get you on the schedule." output: {"action":"accept_scheduling_ask","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer accepts coming in, no day or time named","confidence":0.93}',
  'input: "Customer: That would be great" history: "out: Want me to set up a time for you to come take a look at it?" output: {"action":"accept_scheduling_ask","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer accepts coming in, no day or time named","confidence":0.93}',
  'input: "Customer: Yes" history: "out: We have the 250 Years of Freedom party Sat, July 18, 12-5PM. Want me to save you a spot?" output: {"action":"accept_scheduling_ask","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"july 18","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer accepts july 18, no time named","confidence":0.92}',
  // ACCEPTING OUR OWN OFFER TO SEND SOMETHING — not a visit, and emphatically not a sign-off.
  // The dividing line against the sign-off pairs below is whether the dealer COMMITTED or ASKED:
  // "I'll get those photos over" is already promised and the yes adds nothing; "I can grab a few
  // photos if you want" is waiting on exactly this yes, and going quiet strands the lead.
  'input: "Customer: That would be great" history: "out: I can also check current incentives on the Street Glide Limited and send only what applies." output: {"action":"accept_offer_of_information","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer accepts the offer to send current incentives","confidence":0.93}',
  'input: "Customer: That would be great" history: "out: I can grab a few photos of that Street Glide and text them over if you want." output: {"action":"accept_offer_of_information","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer accepts the offer to send photos","confidence":0.93}',
  'input: "Customer: Yes please" history: "out: If helpful, I can send a simple compare and next-step options." output: {"action":"accept_offer_of_information","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer accepts the offer to send a compare","confidence":0.92}',
  // CONTRAST PAIRS: identical words, non-scheduling outbound → still a sign-off.
  'input: "Customer: Sounds good" history: "out: I\'ll keep you posted as soon as it lands." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.95}',
  'input: "Customer: Sounds great!" history: "out: No problem at all — I\'ll get those photos over to you shortly." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.94}',
  'input: "Customer: Good morning saturday would work best. let me know what time works for you." output: {"action":"ask_for_available_times","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"saturday","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"saturday","confidence":0.95}',
  'input: "Customer: tomorrow around 11/12 would work best for me" output: {"action":"ask_for_available_times","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"tomorrow","time_text":"around 11/12","time_window":"range"},"reference":"none","normalized_text":"tomorrow around 11/12","confidence":0.94}',
  'input: "Customer: Monday, 15 June around 10am" history: "out: I can line up the test ride. What day and time works best?" output: {"action":"ask_for_available_times","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"june 15","time_text":"around 10am","time_window":"exact"},"reference":"none","normalized_text":"monday june 15 around 10:00 AM","confidence":0.95}',
  'input: "Customer: Afternoon would be great" history: "out: I can have our sales team meet you Saturday. Do mornings or afternoons work better for you?" output: {"action":"ask_for_available_times","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"saturday","time_text":"afternoon","time_window":"range"},"reference":"last_outbound","normalized_text":"saturday afternoon","confidence":0.95}',
  'input: "Customer: Can I come at 12 1230" history: "out: I have Fri 3:00 PM, Fri 5:00 PM, or Sat 11:30 AM — do any of those work?" output: {"action":"ask_for_available_times","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"friday","time_text":"12:30","time_window":"exact"},"reference":"last_outbound","normalized_text":"friday 12:30","confidence":0.9}',
  'input: "Customer: Hey is my appointment today Dalton Magill ?" appointment_status: "confirmed" output: {"action":"appointment_status_question","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"today","time_text":"","time_window":"unknown"},"reference":"last_appointment","normalized_text":"customer asks whether appointment is today","confidence":0.96}',
  'input: "Customer: Are we still on for today?" appointment_status: "confirmed" output: {"action":"appointment_status_question","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"today","time_text":"","time_window":"unknown"},"reference":"last_appointment","normalized_text":"customer asks whether existing appointment is still on today","confidence":0.95}',
  'input: "Customer: Will stone be there?" history: "out: Join us Sat, July 18, 12–5PM at American Harley-Davidson for our 250 Years of Freedom party" output: {"action":"staff_availability_question","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"saturday","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer asks whether Stone will be at the store on Saturday","staff_name":"stone","confidence":0.95}',
  'input: "Customer: Is Mike working tomorrow?" output: {"action":"staff_availability_question","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"tomorrow","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"customer asks whether Mike is working tomorrow","staff_name":"mike","confidence":0.95}',
  'input: "Customer: will you be in on Sunday?" output: {"action":"staff_availability_question","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"sunday","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"customer asks whether the rep will be in on Sunday","staff_name":"","confidence":0.92}',
  'input: "Customer: Should I bring the bike and cash with me to my appointment Monday?" appointment_status: "confirmed" output: {"action":"none","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"monday","time_text":"","time_window":"unknown"},"reference":"last_appointment","normalized_text":"customer asks what to bring to the appointment (trade bike and cash down)","confidence":0.95}',
  'input: "Customer: Thursday looks like the next nice day, let me find a ride and I’ll give you a time frame" history: "out: What day/time works for you to come in and pick it up?" output: {"action":"customer_will_provide_time","explicit_action":true,"should_reply":false,"should_book":false,"requested":{"day":"thursday","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"thursday, customer will give time frame","confidence":0.96}',
  'input: "Customer: Let me do some figuring out and will let you know soon" history: "out: What day/time works for you to come in and pick it up?" output: {"action":"customer_will_provide_time","explicit_action":true,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"customer will let us know soon","confidence":0.95}',
  'input: "Customer: 1-2 o’clock ish" history: "out: What time works for you today?" output: {"action":"purchase_delivery_update","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"1-2 o’clock-ish","time_window":"range"},"reference":"last_outbound","normalized_text":"1-2 o’clock-ish","confidence":0.93}',
  'input: "Customer: be there at nine am" history: "out: ok I am around tomorrow or Friday just give me a heads up" output: {"action":"purchase_delivery_update","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"9:00 AM","time_window":"exact"},"reference":"last_outbound","normalized_text":"be there at 9:00 AM","confidence":0.96}',
  'input: "Customer: I will try to be in there by 9:30" history: "out: No worries—we open up at 9am on Saturday, what time were you thinking on coming in?" output: {"action":"confirm_proposed_appointment","explicit_action":true,"should_reply":true,"should_book":true,"requested":{"day":"saturday","time_text":"9:30 AM","time_window":"exact"},"reference":"last_outbound","normalized_text":"saturday 9:30 AM","confidence":0.9}',
  'input: "Customer: probably around 10" history: "out: What time works for you to come in on Monday?" output: {"action":"confirm_proposed_appointment","explicit_action":true,"should_reply":true,"should_book":true,"requested":{"day":"monday","time_text":"10:00 AM","time_window":"exact"},"reference":"last_outbound","normalized_text":"monday 10:00 AM","confidence":0.9}',
  'input: "Customer: On my way doing my best to be there by 530" output: {"action":"provide_arrival_window","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"by 5:30","time_window":"range"},"reference":"none","normalized_text":"on my way by 5:30","confidence":0.95}',
  'input: "Customer: are you guys available anytime later on the day? I don\'t think I\'ll be out until after 3 tomorrow" history: "out: Want to set up a time to swing by and take a look?" output: {"action":"ask_for_available_times","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"tomorrow","time_text":"after 3","time_window":"range"},"reference":"none","normalized_text":"tomorrow after 3","confidence":0.95}',
  'input: "Customer: Ok I will be there for the taste of country pre party on Saturday 👍" output: {"action":"none","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"saturday","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"committing to a saturday event visit","confidence":0.9}',
  'input: "Customer: I can come now" history: "out: When would you like to come in and finalize?" output: {"action":"immediate_arrival_request","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"today","time_text":"now","time_window":"unknown"},"reference":"none","normalized_text":"today now","on_site":false,"confidence":0.96}',
  'input: "Customer: can I come right now?" history: "out: What time works best to stop in?" output: {"action":"immediate_arrival_request","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"today","time_text":"right now","time_window":"unknown"},"reference":"none","normalized_text":"today right now","on_site":false,"confidence":0.96}',
  'input: "Customer: Hey I\'m here who do I ask for?" history: "out: Come by whenever works for you." output: {"action":"immediate_arrival_request","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"today","time_text":"now","time_window":"unknown"},"reference":"none","normalized_text":"customer is at the dealership now and asks who to ask for","on_site":true,"confidence":0.97}',
  'input: "Customer: Talk soon!" history: "out: You’re welcome — happy to help, talk soon!" output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.97}',
  'input: "Customer: Cool" history: "out: Sounds good — thanks for the update." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.96}',
  'input: "Customer: Yes sir" history: "out: I’ll keep you posted." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.96}',
  'input: "Customer: Thanks, will do!" history: "out: Let me know if anything changes." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.96}',
  'input: "Customer: Cool figured that would help with some of the process." history: "out: That should help with finance." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.94}',
  'input: "Customer: Definitely not urgent and I don’t mean to bug you during the long weekend. Hope you’re enjoying it!" history: "out: I’ll check on that for you." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.95}',
  'input: "Customer: Ok great!" history: "out: I’ll keep you posted." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.96}',
  'input: "Customer: Perfect." history: "out: Awesome, glad that works for you!" output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.95}',
  'input: "Customer: Ok 👍" history: "out: Sounds good. Thanks for letting me know." output: {"action":"no_response_needed","explicit_action":false,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.96}',
  'input: "Customer: Thanks, can you send photos?" output: {"action":"none","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"","confidence":0.9}',
  // NAMING YOUR OWN SHIFT IS THE CUSTOMER COMING BACK — not a sign-off, not a promise of a time.
  // +17169400722, 2026-08-06: Scott voicemailed a live credit-app deal ("call back, or text if
  // easier"); "Hey buddy just got up I work over nights" got SILENCE. Over 6 runs on that exact
  // turn the parser flipped no_response_needed / customer_will_provide_time / neutral_ack — two
  // of the three are silence terminals, so an unlucky sample loses the reply. Pin the REPLY.
  'input: "Customer: Hey buddy just got up I work over nights" history: "out: Hey Chris, this is Scott from American Harley-Davidson. I was texting you back and forth this morning about the credit application. Figured I\'d give you a call to go over some information — if you could give me a callback at this number. If text is easier, just let me know." output: {"action":"neutral_ack","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer answers the outreach and says he works overnights","confidence":0.9}',
  'input: "Customer: Just woke up, I work third shift" history: "out: Tried you on the phone — what is the best way to reach you?" output: {"action":"neutral_ack","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer answers the outreach and says he works third shift","confidence":0.9}',
  'input: "Customer: sorry just seeing this, I work nights" history: "out: Just following up on the numbers we went over — let me know if you want me to keep going." output: {"action":"neutral_ack","explicit_action":true,"should_reply":true,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"last_outbound","normalized_text":"customer re-engages late and says he works nights","confidence":0.88}',
  // CONTRAST: the same shift talk WITH an explicit promise to come back with a time really is
  // customer_will_provide_time. The difference is the promise, never the mention of hours.
  'input: "Customer: I work nights so let me look at my schedule and I\'ll text you a time" history: "out: What day works for you to come in?" output: {"action":"customer_will_provide_time","explicit_action":true,"should_reply":false,"should_book":false,"requested":{"day":"","time_text":"","time_window":"unknown"},"reference":"none","normalized_text":"customer will text a time once he checks his schedule","confidence":0.94}'
];
