#!/usr/bin/env python3
"""Run a saved LeadRider MDF portal task with browser-use.

This script is intentionally conservative:
- it uses the prompt generated by the TypeScript runner,
- it may fill a portal draft and upload files,
- it must not final-submit an MDF claim.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run an MDF portal draft task with browser-use.")
    parser.add_argument("--prompt", required=True, help="Markdown prompt file generated by the MDF runner.")
    parser.add_argument("--portal-url", required=True, help="Portal URL to open before running the task.")
    parser.add_argument("--result", required=True, help="Path to write JSON result summary.")
    parser.add_argument("--cdp-url", default="", help="Optional Chrome DevTools Protocol URL for logged-in Chrome.")
    parser.add_argument("--files-dir", default="", help="Local dir of downloaded packet files the agent may upload.")
    parser.add_argument("--max-steps", type=int, default=int(os.getenv("MDF_BROWSER_USE_MAX_STEPS", "35")))
    return parser.parse_args()


def choose_llm():
    try:
        from browser_use import ChatOpenAI
    except Exception as exc:  # pragma: no cover - depends on local browser-use install
        raise RuntimeError("browser-use is installed, but ChatOpenAI could not be imported.") from exc

    model = os.getenv("MDF_BROWSER_USE_MODEL") or os.getenv("OPENAI_MODEL") or "gpt-5"
    return ChatOpenAI(model=model)


async def run() -> int:
    args = parse_args()
    prompt_path = Path(args.prompt)
    result_path = Path(args.result)

    try:
        from browser_use import Agent, Browser
    except ModuleNotFoundError as exc:
        result_path.parent.mkdir(parents=True, exist_ok=True)
        result_path.write_text(
            json.dumps(
                {
                    "ok": False,
                    "blocked": True,
                    "summary": (
                        "browser-use is not installed in this Python environment. "
                        "Install it before running the automatic MDF portal agent."
                    ),
                    "error": str(exc),
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return 2

    if not prompt_path.exists():
        raise FileNotFoundError(f"Prompt file not found: {prompt_path}")

    prompt = prompt_path.read_text(encoding="utf-8")

    available_file_paths: list[str] = []
    if args.files_dir:
        files_dir = Path(args.files_dir)
        if files_dir.is_dir():
            available_file_paths = [str(p) for p in sorted(files_dir.iterdir()) if p.is_file()]

    files_note = (
        "These local files are available to your upload action — attach them to the form's "
        '"Upload File" inputs: ' + ", ".join(available_file_paths)
        if available_file_paths
        else "No local files were provided for upload; do not block on file uploads."
    )

    task = "\n\n".join(
        [
            f"Open this URL first: {args.portal_url}",
            (
                "Follow the navigation and form rules in the task below EXACTLY. Do not read, type, "
                "copy, reveal, or transmit any credentials; if a sign-in page needs input and Chrome "
                "autofill is not already present, stop for manual login."
            ),
            files_note,
            prompt,
            (
                'Important final rule: to save the draft click "Save for Later". NEVER click "Submit". '
                "Stop at draft/review and report exactly what was filled, what was uploaded, and what remains."
            ),
        ]
    )

    browser_kwargs: dict[str, object] = {"headless": False}
    if args.cdp_url:
        browser_kwargs["cdp_url"] = args.cdp_url
    elif os.getenv("MDF_BROWSER_USE_CLOUD", "").strip() in {"1", "true", "yes"}:
        browser_kwargs["use_cloud"] = True

    llm = choose_llm()
    browser = Browser(**browser_kwargs)
    agent = Agent(task=task, llm=llm, browser=browser, available_file_paths=available_file_paths)
    history = await agent.run(max_steps=max(5, args.max_steps))

    summary = str(history)
    result_path.parent.mkdir(parents=True, exist_ok=True)
    result_path.write_text(
        json.dumps(
            {
                "ok": True,
                "blocked": False,
                "summary": summary[-6000:],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(asyncio.run(run()))
    except Exception as exc:
        result_path_raw = ""
        if "--result" in sys.argv:
            try:
                result_path_raw = sys.argv[sys.argv.index("--result") + 1]
            except Exception:
                result_path_raw = ""
        if result_path_raw:
            path = Path(result_path_raw)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                json.dumps({"ok": False, "blocked": True, "summary": str(exc), "error": repr(exc)}, indent=2),
                encoding="utf-8",
            )
        print(str(exc), file=sys.stderr)
        raise SystemExit(1)
