#!/usr/bin/env python3
"""Run a conservative browser-use rescue task for TLP CRM updates.

The TypeScript Playwright connector remains the primary TLP path. This runner is
only for rescue when deterministic selectors fail.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a LeadRider TLP CRM browser-use rescue task.")
    parser.add_argument("--prompt", required=True, help="Markdown prompt file generated by LeadRider.")
    parser.add_argument("--portal-url", required=True, help="TLP portal URL to open first.")
    parser.add_argument("--result", required=True, help="Path to write JSON result summary.")
    parser.add_argument("--cdp-url", default="", help="Optional Chrome DevTools Protocol URL for logged-in Chrome.")
    parser.add_argument("--max-steps", type=int, default=int(os.getenv("TLP_BROWSER_USE_MAX_STEPS", "35")))
    return parser.parse_args()


def choose_llm():
    try:
        from browser_use import ChatOpenAI
    except Exception as exc:  # pragma: no cover - depends on local browser-use install
        raise RuntimeError("browser-use is installed, but ChatOpenAI could not be imported.") from exc

    model = os.getenv("TLP_BROWSER_USE_MODEL") or os.getenv("OPENAI_MODEL") or "gpt-5"
    return ChatOpenAI(model=model)


async def run() -> int:
    args = parse_args()
    prompt_path = Path(args.prompt)
    result_path = Path(args.result)

    try:
        from browser_use import Agent, Browser
    except ModuleNotFoundError as exc:
        result_path.parent.mkdir(parents=True, exist_ok=True)
        result_path.write_text(
            json.dumps(
                {
                    "ok": False,
                    "blocked": True,
                    "summary": (
                        "browser-use is not installed in this Python environment. "
                        "Install it before running the automatic TLP CRM rescue agent."
                    ),
                    "error": str(exc),
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return 2

    if not prompt_path.exists():
        raise FileNotFoundError(f"Prompt file not found: {prompt_path}")

    prompt = prompt_path.read_text(encoding="utf-8")
    task = "\n\n".join(
        [
            f"Open this TLP CRM portal URL first: {args.portal_url}",
            (
                "Login rule: if TLP login, Microsoft login, password, or MFA appears, stop and report "
                "that manual login is needed unless Chrome has already autofilled saved credentials. "
                "If saved autofill is already present, you may click Next, Continue, Sign in, or Yes. "
                "Do not read, type, copy, reveal, or transmit credentials."
            ),
            prompt,
            "Final rule: only save the exact internal CRM update described above. Do not message the customer.",
        ]
    )

    browser_kwargs: dict[str, object] = {"headless": False}
    if args.cdp_url:
        browser_kwargs["cdp_url"] = args.cdp_url
    elif os.getenv("TLP_BROWSER_USE_CLOUD", "").strip().lower() in {"1", "true", "yes"}:
        browser_kwargs["use_cloud"] = True

    llm = choose_llm()
    browser = Browser(**browser_kwargs)
    agent = Agent(task=task, llm=llm, browser=browser)
    history = await agent.run(max_steps=max(5, args.max_steps))

    summary = str(history)
    result_path.parent.mkdir(parents=True, exist_ok=True)
    result_path.write_text(
        json.dumps(
            {
                "ok": True,
                "blocked": False,
                "summary": summary[-6000:],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(asyncio.run(run()))
    except Exception as exc:
        result_path_raw = ""
        if "--result" in sys.argv:
            try:
                result_path_raw = sys.argv[sys.argv.index("--result") + 1]
            except Exception:
                result_path_raw = ""
        if result_path_raw:
            path = Path(result_path_raw)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                json.dumps({"ok": False, "blocked": True, "summary": str(exc), "error": repr(exc)}, indent=2),
                encoding="utf-8",
            )
        print(str(exc), file=sys.stderr)
        raise SystemExit(1)
